defaults:
  - model: tts
  - metrics: empty_metrics
  - datasets: text_dataset
  - dataloader: inference
  - transforms: empty_transforms
  - writer: wandb
  - _self_
inferencer:
  device_tensors: []
  device: auto
  save_path: "inference_result/tts"
  seed: 1
  from_pretrained: "saved/tts_model_best.pth"
  wandb_logging: False
