defaults:
  - model: tts
  - metrics: empty_metrics
  - datasets: custom_text
  - dataloader: inference
  - transforms: only_batch
  - _self_
inferencer:
  device_tensors: []
  device: auto
  save_path: "inference_result/tts"
  seed: 1
  from_pretrained: "saved/tts_model_best.pth"
