defaults:
  - model: hifigan
  - metrics: empty_metrics
  - datasets: text_dataset
  - dataloader: inference
  - transforms: only_batch
  - _self_
inferencer:
  device_tensors: ["gt_audio", "gt_melspec"]
  device: auto
  save_path: "inference_result/vocoder"
  seed: 1
  from_pretrained: "saved/model_best.pth"
